#Before running this compose file make sure download both frontEnd and backEnd images from dokerhub
#==> BackEnd img : docker pull kaifk468/online-exam-back
#==> FrontEnd img : docker pull kaifk468/online-exam-front
services:
  postgres:
    container_name: DatatBase-Cont
    image: postgres:alpine3.18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: onlineexam
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
     - C:\Users\shivamjais\Desktop\WorkSpace\Docker\DockerVolume:/var/lib/postgresql/data
    restart: always
    networks:
      - mynetwork

  spring-app:
    container_name: BackEnd-Cont
    image: kaifk468/online-exam-back
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - mynetwork
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/onlineexam
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    restart: always

  angular-app:
    container_name: UI-Cont
    image: kaifk468/online-exam-front
    ports:
      - "4200:4200"
    depends_on:
      - spring-app
    networks:
      - mynetwork
    restart: always

networks:
  mynetwork:

